language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - "pip install -qq flake8"
  - "pip install ."

# command to run tests
script:
  - nosetests -s -v
  - flake8 --ignore E501 constraint examples tests
